#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     leftside,       sensorI2CMuxController)
#pragma config(Sensor, S2,     rightside,      sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     backLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     manipRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     manipLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    armManip1,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    armManip2,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    gateManip,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"




task main()
{

}
