#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     leftside,       sensorI2CMuxController)
#pragma config(Sensor, S2,     rightside,      sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     frontLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     backLeft,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    mainmanip1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    mainmanip2,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")
/**!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/



/*Last edited Thursday Jan. 29, most current version as of Monday Feb 2*/



/*
Mecanum drive with Deadsone thresholds, gives the driver room for error when centering circle pads
		-Left circle-pad
				y-axis moves robot along y-axis
				x-axis moves robot along x-axis
					diagonally uses both axis'
		-Right circle-pad
				rotate robot according to x-axis
*/

task main()
{
/*Loop Forever*/
while(1 == 1)

getJoystickSettings(joystick);
    motor[frontRight] = joystick.joy1_y1;
   	motor[backRight] = joystick.joy1_y1;
    motor[frontLeft] = joystick.joy1_y1;
    motor[backLeft] = joystick.joy1_y1;
getJoystickSettings(joystick);
		motor[frontRight] = joystick.joy1_x1;
		motor[backRight] = joystick.joy1_x1;
		motor[frontLeft] = joystick.joy1_x1;
		motor[backLeft] = joystick.joy1_x1;
getJoystickSettings(joystick);
		motor[frontRight] = joystick.joy1_y2;
		motor[backRight] = joystick.joy1_y2;
		motor[frontLeft] = joystick.joy1_y2;
		motor[backLeft] = joystick.joy1_y2;
getJoystickSettings(joystick);
		motor[frontRight] = joystick.joy1_x2;
		motor[backRight] = joystick.joy1_x2;
		motor[frontLeft] = joystick.joy1_x2;
		motor[backLeft] = joystick.joy1_x2;

	if (joystick.joy1_y1 < -15 && joystick.joy1_y1 > 15)
			/*don't move on y-axis without input*/
		motor[frontRight] = 0;
		motor[backRight] = 0;
		motor[frontLeft] = 0;
		motor[backLeft] = 0;
	if (joystick.joy1_x1 < -15 && joystick.joy1_x1 > 15)
			/*don't move on x-axis without input*/
		motor[frontRight] = 0;
		motor[backRight] = 0;
		motor[frontLeft] = 0;
		motor[backLeft] = 0;

		if (joystick.joy1_y1 < -128 && joystick.joy1_y1 > 15)
			/*move forward*/
		motor[frontRight] = -10;
		motor[backRight] = -10;
		motor[frontLeft] = -10;
		motor[backLeft] = -10;
	if (joystick.joy1_y1 < 127 && joystick.joy1_y1 > 15)
			/*move backwards*/
		motor[frontRight] = 10;
		motor[backRight] = 10;
		motor[frontLeft] = 10;
		motor[backLeft] = 10;

	if (joystick.joy1_x1 < 127 && joystick.joy1_x1 > 15)
			/*move right*/
		motor[frontRight] = 10;
		motor[backRight] = -10;
		motor[frontLeft] = -10;
		motor[backLeft] = 10;
	if (joystick.joy1_x1 < -128 && joystick.joy1_x1 > -15)
			/*move left*/
		motor[frontRight] = -10;
		motor[backRight] = 10;
		motor[frontLeft] = 10;
		motor[backLeft] = -10;

	if(joystick.joy1_x2 < 15 && joystick.joy1_x2 > -15)
			/*do not rotate*/
		motor[frontRight] = 0;
		motor[backRight] = 0;
		motor[frontLeft] = 0;
		motor[backLeft] = 0;
	if(joystick.joy1_x2 < 127 && joystick.joy1_x2 > 15)
			/*rotate right*/
		motor[frontRight] = 10;
		motor[backLeft] = 10;
		motor[frontRight] = -10;
		motor[backRight] = -10;
	if(joystick.joy1_x2 < -15 && joystick.joy1_x2 > -128)
			/*rotate left*/
		motor[frontRight] = -10;
		motor[backRight] = -10;
		motor[frontLeft] = 10;
		motor[backLeft] = 10;
}
