#pragma config(Motor,  motorA,          LeftMotor1,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          RightMotor1,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          ManMotor1,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main() {

	while(1==1)
	{
		getJoystickSettings(joystick);
		motor[LeftMotor1] = joystick.joy1_y1/2;
		motor[RightMotor1] = joystick.joy1_y2/2;
		/*motor[LeftMotor2] = joystick.joy1_y1/2;
		motor[RightMotor2] = joystick.joy1_y2/2;*/
	}
	if(joystick.joy1_y1 <   10 && joystick.joy1_y1 > -10)
	{
		motor[LeftMotor1] = 0;
		/*motor[LeftMotor2] = 0;*/
	}
	else
	{
		motor[LeftMotor1] = joystick.joy1_y1/2;
		/*motor[LeftMotor2] = joystick.joy1_y1/2;*/
	}
	if(joystick.joy1_y2 <   10 && joystick.joy1_y2 > -10)
	{

		motor[RightMotor1] = 0;
		/*	motor[RightMotor2] = 0;*/
	}
	else
	{
		motor[RightMotor1] = joystick.joy1_y2/2;
		/*motor[RighttMotor2] = joystick.joy1_y2/2;*/
	}
	if
		(joy1Btn(1) ==1)
	{
		motor[ManMotor1]= 50;
	}
	if
		(joy1Btn(3) ==1)
	{
		motor[ManMotor1]= -50;
	}
	if(joy1Btn(1) ==0 && joy1Btn(3) ==0)
	{
		motor[ManMotor1] = 0;
	}
}







/*}int main
{
motor(LeftMotor1) = 100;
motor(RightMotor1) = -100;
motor(LeftMotor2) = 100;*/
