#pragma config(Motor,  motorA,          RightMotor2,   tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[RightMotor2] = 80;
	wait1Msec(1000);
}
